export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const GET_INSTITUTIONS_SUCCESS = 'GET_INSTITUTIONS_SUCCESS';
export const GET_INSTITUTIONS_ERROR = 'GET_INSTITUTIONS_ERROR';

export const GET_INSTITUTION_SUCCESS = 'GET_INSTITUTION_SUCCESS';
export const GET_INSTITUTION_ERROR = 'GET_INSTITUTION_ERROR';

export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';
export const GET_IMAGES_ERROR = 'GET_IMAGES_ERROR';

export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
export const POST_REVIEW_ERROR = 'POST_REVIEW_ERROR';

export const POST_IMAGE_SUCCESS = 'POST_IMAGE_SUCCESS';
export const POST_IMAGE_ERROR = 'POST_IMAGE_ERROR';

export const POST_INST_SUCCESS = 'POST_INST_SUCCESS';
export const POST_INST_ERROR = 'POST_INST_ERROR';

export const DELETE_INST_SUCCESS = 'DELETE_INST_SUCCESS';
export const DELETE_INST_ERROR = 'DELETE_INST_ERROR';

export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_ERROR = 'DELETE_IMAGE_ERROR';

export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_ERROR = 'DELETE_REVEIW_ERROR';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';